server.port=8080

spring.application.name=api-gateway

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

spring.cloud.gateway.discovery.locator.enabled=true
spring.cloud.gateway.discovery.locator.lower-case-service-id=true

spring.cloud.gateway.routes[0].id=auth-service
spring.cloud.gateway.routes[0].uri=lb://AUTH-SERVICE
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/auth/**

spring.cloud.gateway.routes[1].id=quantity-service
spring.cloud.gateway.routes[1].uri=lb://QUANTITY-SERVICE
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/v1/quantities/**

spring.cloud.gateway.routes[2].id=history-service
spring.cloud.gateway.routes[2].uri=lb://HISTORY-SERVICE
spring.cloud.gateway.routes[2].predicates[0]=Path=/api/v1/measurements/**

spring.cloud.gateway.routes[3].id=auth-oauth2
spring.cloud.gateway.routes[3].uri=lb://AUTH-SERVICE
spring.cloud.gateway.routes[3].predicates[0]=Path=/oauth2/**

spring.cloud.gateway.routes[4].id=auth-oauth2-callback
spring.cloud.gateway.routes[4].uri=lb://AUTH-SERVICE
spring.cloud.gateway.routes[4].predicates[0]=Path=/login/oauth2/code/**

logging.level.org.springframework.cloud.gateway=DEBUG
