server.port=${PORT:${SERVER_PORT:8761}}

spring.config.import=optional:file:.env[.properties],optional:file:eureka-server/.env[.properties]

eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false

logging.level.com.netflix.eureka=${LOGGING_LEVEL_COM_NETFLIX_EUREKA:OFF}
logging.level.com.netflix.discovery=OFF
